
const level1 = () => {
    const currentLevel = 1;
    const levelEnd = 2000;
    return (
        new Level(
            enemies = [
                new Jellyfish1(levelEnd),
                new Pufferfish(levelEnd),
                new Jellyfish2(levelEnd),
                new Jellyfish1(levelEnd),
                new Pufferfish(levelEnd),
                new Jellyfish2(levelEnd),
                new Jellyfish1(levelEnd),
                new Pufferfish(levelEnd),
                new Jellyfish2(levelEnd),
                new Jellyfish1(levelEnd),
                new Pufferfish(levelEnd),
                new Jellyfish2(levelEnd),
                new Whale(levelEnd)
            ],
            collectables = [
                new Bubble(levelEnd),
                new Bubble(levelEnd),
                new Bubble(levelEnd),
                new Bubble(levelEnd),
                new Bubble(levelEnd),
                new Bubble(levelEnd),
                new Bubble(levelEnd),
                new Bubble(levelEnd),
                new Bubble(levelEnd),
                new Bubble(levelEnd),
                new Bubble(levelEnd),
                new Bubble(levelEnd),
                new Coin(Math.random() * levelEnd, 340 + Math.random() * 60),
                new Coin(Math.random() * levelEnd, 340 + Math.random() * 60),
                new Coin(Math.random() * levelEnd, 340 + Math.random() * 60),
                new Coin(Math.random() * levelEnd, 340 + Math.random() * 60),
                new Coin(Math.random() * levelEnd, 340 + Math.random() * 60),
                new Coin(Math.random() * levelEnd, 340 + Math.random() * 60),
                new Coin(Math.random() * levelEnd, 340 + Math.random() * 60),
                new Coin(Math.random() * levelEnd, 340 + Math.random() * 60),
                new Coin(Math.random() * levelEnd, 340 + Math.random() * 60),
                new Coin(Math.random() * levelEnd, 340 + Math.random() * 60),
                new Coin(Math.random() * levelEnd, 340 + Math.random() * 60),
                new Coin(Math.random() * levelEnd, 340 + Math.random() * 60),
                new Coin(Math.random() * levelEnd, 340 + Math.random() * 60),
                new Coin(Math.random() * levelEnd, 340 + Math.random() * 60),
                new Coin(Math.random() * levelEnd, 340 + Math.random() * 60),
                new Coin(Math.random() * levelEnd, 340 + Math.random() * 60),
                new Coin(Math.random() * levelEnd, 340 + Math.random() * 60),
                new Coin(Math.random() * levelEnd, 340 + Math.random() * 60),
                new Coin(Math.random() * levelEnd, 340 + Math.random() * 60),
                new Coin(Math.random() * levelEnd, 340 + Math.random() * 60),
                new Coin(Math.random() * levelEnd, 340 + Math.random() * 60),
                new Coin(Math.random() * levelEnd, 340 + Math.random() * 60),
                new Coin(Math.random() * levelEnd, 340 + Math.random() * 60),
                new Coin(Math.random() * levelEnd, 340 + Math.random() * 60),
                new Coin(Math.random() * levelEnd, 340 + Math.random() * 60),
                new Coin(Math.random() * levelEnd, 340 + Math.random() * 60),
                new Coin(Math.random() * levelEnd, 340 + Math.random() * 60),
                new Coin(Math.random() * levelEnd, 340 + Math.random() * 60),
                new Coin(Math.random() * levelEnd, 340 + Math.random() * 60),
                new Coin(Math.random() * levelEnd, 340 + Math.random() * 60),
                new Coin(Math.random() * levelEnd, 340 + Math.random() * 60),
                new Coin(Math.random() * levelEnd, 340 + Math.random() * 60),
                new Coin(Math.random() * levelEnd, 340 + Math.random() * 60),
                new Poison(Math.random() * levelEnd, 360 + Math.random() * 40),
                new Poison(Math.random() * levelEnd, 360 + Math.random() * 40),
                new Poison(Math.random() * levelEnd, 360 + Math.random() * 40),
                new Poison(Math.random() * levelEnd, 360 + Math.random() * 40),
                new Poison(Math.random() * levelEnd, 360 + Math.random() * 40),
                new Poison(Math.random() * levelEnd, 360 + Math.random() * 40),
            ],
            backgroundObjects = [
                new Background('../Sharkie/img/bg/Layers/5. Water/D1.png', -719),
                new Background('../Sharkie/img/bg/Layers/5. Water/D2.png', 0),
                new Background('../Sharkie/img/bg/Layers/5. Water/D1.png', 719),
                new Background('../Sharkie/img/bg/Layers/5. Water/D2.png', 2 * 719),
                new Background('../Sharkie/img/bg/Layers/5. Water/D1.png', 3 * 719),

                new Background('../Sharkie/img/bg/Layers/3.Fondo 1/D1.png', -719),
                new Background('../Sharkie/img/bg/Layers/3.Fondo 1/D2.png', 0),
                new Background('../Sharkie/img/bg/Layers/3.Fondo 1/D1.png', 719),
                new Background('../Sharkie/img/bg/Layers/3.Fondo 1/D2.png', 2 * 719),
                new Background('../Sharkie/img/bg/Layers/3.Fondo 1/D1.png', 3 * 719),

                new Background('../Sharkie/img/bg/Layers/4.Fondo 2/D1.png', -719),
                new Background('../Sharkie/img/bg/Layers/4.Fondo 2/D2.png', 0),
                new Background('../Sharkie/img/bg/Layers/4.Fondo 2/D1.png', 719),
                new Background('../Sharkie/img/bg/Layers/4.Fondo 2/D2.png', 2 * 719),
                new Background('../Sharkie/img/bg/Layers/4.Fondo 2/D1.png', 3 * 719),

                new Background('../Sharkie/img/bg/Layers/2. Floor/D1.png', -719),
                new Background('../Sharkie/img/bg/Layers/2. Floor/D2.png', 0),
                new Background('../Sharkie/img/bg/Layers/2. Floor/D1.png', 719),
                new Background('../Sharkie/img/bg/Layers/2. Floor/D2.png', 2 * 719),
                new Background('../Sharkie/img/bg/Layers/2. Floor/D1.png', 3 * 719),

            ],
            firedBubbles = [

            ],
            statusBars = [
                new HealthBar()
            ],
            levelEnd,
            currentLevel
        ))
}